filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.pipeline: with_plugins
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log*"]
# - module: nginx-request-body
#   requestbody:
#     enabled: true
#     var.paths: ["/var/log/nginx/requestbody.log*"]
filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/nginx/requestbody.log
  document_type: nginx-request-body
output.logstash:
  hosts: ["logstash:5044"]
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   protocol: "http"
#   username: "filebeat"
#   password: "123456"
#   index: "test-%{+yyyy.MM.dd}"
logging.to_files: true
logging.files:
#### for debugging
# logging.level: debug
# logging.selectors: ["*"]
#### end of for debugging

# comments above are an attempt to process modified nginx logs via a custom filebeat publishing directly to elastic search but failed. so using logstash instead for that purpose.
